name               = "personal-finance-worker"
account_id         = "d28ac155f2c89c0847e96ae8a961c666"
workers_dev        = false
compatibility_date = "2024-05-23"
main               = "worker.js"

route   = "tractionfi.com/*"

kv_namespaces = [
  { binding = "USER_DATA", id = "026e48cfe49f4e65a853400cda9ec5df" }
]

[build]
command = "npm run build"

[assets]
directory = "./out"
binding   = "ASSETS"
